if [ -e "$HOME/.profile ]; then
    source "$HOME/.profile"
fi

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Prompt
function parse_git_dirty() {
    [[ $(git status 2> /dev/null | tail -n1) != "nothing to commit, working directory clean" ]] && echo "*"
}
function parse_git_branch() {
    git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(parse_git_dirty)/"
}
PS1="\u@\h:\w\$([[ -n \$(git branch 2> /dev/null) ]] && echo \"(\")\$(parse_git_branch)\$([[ -n \$(git branch 2> /dev/null) ]] && echo \")\")\$ "

# Autocompletion for Homebrew packages
brew --version >/dev/null 2>&1
if [ $? == 0 ]; then
    if [ -d "`brew --prefix`/etc/bash_completion.d" ]; then
        source `brew --prefix`/etc/bash_completion.d/*
    fi
fi

# Activate RVM
RVM_HOME="$HOME/.rvm"
if [ -e "$RVM_HOME/scripts/rvm" ]; then
    source "$RVM_HOME/scripts/rvm"
    if [ -e "$RVM_HOME/scripts/completion" ]; then
        source "$RVM_HOME/scripts/completion"
    fi
fi
